name: node.js CI

on:
  schedule:
    # 매일 아침 9시 30분에 슬랙 알람 발송
    # 시간은 UTC 임
    - cron: "30 22 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - run: npm start
      env:
        CI: true
        WEBHOOKS: ${{ secrets.WEBHOOKS }}
